# Generated by Django 2.2.3 on 2019-08-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_uploadfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='uploads/')),
                ('team_size', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
