# Generated by Django 2.2.3 on 2019-08-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190801_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='gender_select',
            field=models.BooleanField(default=False),
        ),
    ]
