# Generated by Django 2.2.3 on 2019-08-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_fileupload_academic_score_select'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='academic_score_select',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='ethnicity_select',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='gender_select',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='team_size',
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='csv_file',
            field=models.FileField(upload_to=''),
        ),
    ]
