# Generated by Django 2.2.3 on 2019-08-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_savedsolutions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='solutions')),
            ],
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='csv_file',
            field=models.FileField(upload_to='', verbose_name='uploads'),
        ),
        migrations.AlterField(
            model_name='savedsolutions',
            name='csv_file',
            field=models.FileField(upload_to='saved'),
        ),
    ]
