# Generated by Django 2.2.3 on 2019-08-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190810_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='csv_file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='solutions',
            name='csv_file',
            field=models.CharField(max_length=1000000000000),
        ),
    ]
