# Generated by Django 2.2.3 on 2019-08-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190810_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='csv_file',
            field=models.FileField(upload_to='solutions'),
        ),
    ]
