# Generated by Django 2.2.3 on 2019-08-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190810_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsolutions',
            name='name',
            field=models.CharField(default='solution.csv', max_length=100),
        ),
    ]
